spring:
  application:
    name: vacancy-service
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9991}

---
spring:
  config:
    activate:
      on-profile: ${PROFILE:dev}