server:
  port: 0

spring:
  application:
    name: company-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    activate:
      on-profile: ${SPRING_PROFILES_ACTIVE:dev}
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:9991}